version: "3"
services:
  healthcheck:
    build: ../services/healthcheck
    depends_on:
      - wiki
  dithering:
    build: ../services/dithering
    depends_on:
      - wiki
    ports:
      - 3000:3000
  wiki:
    build: ../services/wiki
    ports:
      - 8080:8080
