# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app
EXPOSE 3000

# Copy the package.json and yarn.lock files to the container
COPY package.json yarn.lock ./

# Install the dependencies
RUN yarn install --frozen-lockfile

# Copy the source code to the container
COPY . .

# Build the app
RUN yarn build

# Set the command to run the app
CMD ["yarn", "prod"]
